### ISSUE TITLE
live FaceRecognition with camera?

### ISSUE THREAD

**Issue by AnaabTeam** [AnLaVN/AL-Library#1]

**Comment by AnLaVN** [comment]
It can Face Recognition with camera. Using both of FaceRecognition and FaceDetection.

``` java
FaceRecognition.setImageOrginal("yourPath/yourOriginalPicture.png);
FaceRecognition.setImageTesting(FaceDetection.getBufferedImage());
String result = FaceRecognition.Recognition();
```
At here we set a test image from Buffered Image get from FaceDetection with camera. And dont forget set your original image, it can be a local image or internet image. 
But it CAN'T live Face Recognition, that is imposibble in Java. Sorry about that.
Thank you for your interest in my product, I hope this helps. Thank you very much.

**Comment by AnLaVN** [comment]
I am still looking for a fast and accurate enough solution to Live Face Recognition with camera, but as of now there is no possible way for Java language.

If possible, please visit https://ultralytics.com, a solution for object recognition using YOLO machine learning models, with YOLOv8, the models that are the best in the world at what they do: real-time object detection, classification, and segmentation.

But I'm not sure recognizing a particular face with YOLO is accurate enough. Because you need to train your own YOLO model to detect the object you want. I tried that but it's not what I expected.
